#! /bin/sh
# initialise overview files first time

# =()<. ${NEWSCONFIG-@<NEWSCONFIG>@}>()=
. ${NEWSCONFIG-/usr/etc/news/bin/config}

WORKAROUND=` awk '{print $1}' $NEWSCTL/active | tr . / | sort `
export WORKAROUND 
echo $WORKAROUND

PATH=$NEWSCTL/bin:$NEWSBIN/nov:$NEWSBIN:$NEWSPATH ; export PATH
umask $NEWSUMASK

stamp=$NEWSCTL/time.stamp

verbose=n
case "$1" in
-v)	verbose=y	;;
esac

lock LOCK $$
trap '' 1 2 15
sleep 2
touch $stamp		# anything newer we'll get from relaynews
sleep 2
>$NEWSCTL/headers	# avoid duplicates
unlock LOCK
trap 1 2 15
# after unlocking, relaynews may write new headers, to be processed later
# by domkov

lock LOCKoverview $$
trap "rm -f $stamp ; unlock LOCKoverview ; trap 0 ; exit" 0 1 2 15

# the sort is an attempt to maximise locality of reference in the file system

# Originally this was "for d in ` awk ... `, but the pipeline dumped core
# when started with the whole environment. Assigning the result of the
# pipeline to a variable before the other things the script does 
# allowed this to execute. Probably a result of the restricted address space 
# of the PDP-11. The three commented out lines below are duplicated at the
# top of the script 
#WORKAROUND=` awk '{print $1}' $NEWSCTL/active | tr . / | sort `
#export WORKAROUND 
#echo $WORKAROUND
for d in $WORKAROUND
do
	cd $NEWSARTS
	if test ! -d $d
	then
		continue
	fi
	cd $d
	test " $verbose" = " y" && echo $d
	o=$NEWSOV/$d
	if test ! -d $o
	then
		mkpdir $o
	fi
	# sort -n ensures numeric article order
	ls -f | sort -n | mkov -aio $stamp >$NEWSOV/$d/.overview
done
