#! /bin/sh
# extract staleness in days from $NEWSCTL/explist

# =()<. ${NEWSCONFIG-@<NEWSCONFIG>@}>()=
. ${NEWSCONFIG-/usr/etc/news/bin/config}
PATH=$NEWSCTL/bin:$NEWSBIN:$NEWSPATH; export PATH

(PATH=/bin exec awk '$1 == "/expired/" { print $3 }' $NEWSCTL/explist)
